-- return {
--   "windwp/nvim-autopairs",
--   event = "InsertEnter",
--   config = true,
--   opts = {
--     disable_in_macro = true,
--   },
--   -- use opts = {} for passing setup options
--   -- this is equivalent to setup({}) function
-- }
